### ISSUE TITLE
Possible API change

### ISSUE THREAD

**Issue by fwgreen** [misha/ceylatra#1]
Would you consider an API along these lines?
```Ceylon
get("/:name") (request, response) {
        if (exists name = request.variables["name"],
            exists todo = todos[name]) {
            return todo;
        } else {
            return halt(404);
        }
};
```
This will be possible after https://github.com/ceylon/ceylon-spec/issues/1256 (If enough people demand it) and will require, according to Gavin King, a method signature of:
```Ceylon
void get(String path)(Result(Request,Response) handler) { ... }
```
I have no technical reasons beyond it looking slightly more elegant, plus not ending methods with `})`, looks less like Java.

**Comment by misha** [comment]
Although I'm a big fan of Ruby blocks, I believe Ceylon's facilities for passing functions are strictly more powerful than what blocks may offer. In the above example, it may no longer be obvious where to pass additional functions (like in-lined, per-request transformers/filters/exception handlers).

That being said, I don't see any issues with supporting both syntaxes if block syntax is approved for the (extremely) common case you posted above.

Feel free to re-open if it gets approved. If  I'm not done with V1 of Ceylatra by then, I'll definitely include it in the release.
